version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    versioning-strategy: increase
    schedule:
      interval: weekly
    labels:
      - area/dependencies
    ignore:
      - dependency-name: vite
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitejs/plugin-react"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: maven
    directory: keycloak-theme
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - area/dependencies
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
