version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 999
  schedule:
    interval: weekly
  ignore:
    - dependency-name: jest
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/jest"
      update-types: ["version-update:semver-major"]
    - dependency-name: ts-jest
      update-types: ["version-update:semver-major"]
    - dependency-name: react-hook-form
      update-types: ["version-update:semver-major"]