name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Admin UI
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Install dependencies
      - run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
