name: Publish package
on:
  push:
    branches: [master]
defaults:
  run:
    working-directory: keycloak-theme
jobs:
  publish:
    if: github.repository_owner == 'keycloak'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Admin UI
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
          cache: maven

      - name: Build and deploy Admin UI
      - run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
